<?php

namespace Laradic\Console;

use Illuminate\Console\Application;
use Illuminate\Contracts\Container\Container;
use Illuminate\Contracts\Events\Dispatcher;

class Artisan extends Application
{
    public function __construct(Container $laravel, Dispatcher $events, $version)
    {
        parent::__construct($laravel, $events, $version);
        $this->setName(app()->getName());
    }

    public function getHelp()
    {
        return parent::getHelp(); // TODO: Change the autogenerated stub
    }


}
